from mbentley/omada-controller:5.3
VOLUME ["/config/omada"]
RUN mkdir -p /config/omada/data
RUN ln -s /opt/tplink/EAPController/data /config/omada/data 
RUN mkdir -p /config/omada/work
RUN ln -s /opt/tplink/EAPController/work /config/omada/work 
RUN mkdir -p /config/omada/logs
RUN ln -s /opt/tplink/EAPController/logs /config/omada/logs 


